<a href="https://colab.research.google.com/github/shahdelmasry12/AI-and-ML-labs/blob/main/Python_Numpy_Exercises_with_hints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [63]:
import numpy as np
print(np.__version__)
print(np.show_config)

2.0.2
<function show at 0x7c29a86fb420>


#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [4]:
arr=np.array([6,7,3,4,2])
print(arr)

[6 7 3 4 2]


#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [5]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [6]:
print("Size of the array: ",arr.size)
print("Memory size of one array element in bytes: ",arr.itemsize)

Size of the array:  5
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [7]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 12 but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [12]:
np.zeros(12)
print(np.put(np.zeros(12),6,1))

None


#### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [13]:
my_arr=np.arange(20,60)
print(my_arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`

In [14]:
my_arr[::-1]

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [15]:
arr=np.arange(12,21).reshape(3,3)
print(arr)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

In [16]:
arr=np.array([3,7,0,0,9,0])
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [17]:
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [20]:
my_arr=np.random.random((2,2,2))
print(my_arr)

[[[4.74545182e-01 4.85842432e-01]
  [9.84334133e-01 3.41357727e-01]]

 [[3.56783984e-04 5.03012115e-01]
  [1.63917448e-01 9.94681844e-01]]]


#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [21]:
my_arr=np.random.random((9,9))
print(my_arr)
print("Minimum value: ",my_arr.min())
print("Maximum value: ",my_arr.max())

[[0.27220419 0.68996934 0.67761501 0.54257281 0.71261669 0.8563897
  0.89964151 0.29533986 0.14260423]
 [0.8390074  0.36965241 0.61210213 0.55908846 0.82076778 0.69615852
  0.30255616 0.24653989 0.085484  ]
 [0.74872708 0.15027652 0.36818922 0.38625045 0.96035679 0.29102106
  0.29898676 0.79889494 0.63115675]
 [0.97976035 0.01138948 0.71960568 0.49043189 0.4302257  0.51543584
  0.05314845 0.90882403 0.38664307]
 [0.46911686 0.87310756 0.58526196 0.69643362 0.49548399 0.6890809
  0.35656661 0.52352336 0.03652484]
 [0.628929   0.76189909 0.63532435 0.43353691 0.02428107 0.76584134
  0.26308006 0.90329379 0.23094947]
 [0.64129163 0.05822844 0.11788444 0.76934743 0.00919168 0.45628634
  0.14219269 0.45798099 0.2375943 ]
 [0.78475967 0.50269973 0.94862757 0.44014716 0.76366938 0.41587442
  0.55096785 0.00356247 0.56014538]
 [0.02956809 0.93545082 0.31034097 0.02160071 0.3989986  0.96240419
  0.75436101 0.59226355 0.30690072]]
Minimum value:  0.003562472282315654
Maximum value:  0.9797603466

#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [22]:
arr=np.random.random(20)
print(arr)
print("Mean value: ",arr.mean())

[0.4562634  0.74564823 0.20821875 0.80756584 0.18157609 0.87332985
 0.8298136  0.66386156 0.47258373 0.08058267 0.32502825 0.55101936
 0.22828843 0.55153037 0.10030969 0.78024074 0.10894181 0.89077191
 0.44839984 0.99326331]
Mean value:  0.5148618712198195


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [25]:
arr=np.ones((4,4))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [29]:
my_arr=np.ones((3,3))
print(np.pad(my_arr, pad_width=1, mode='constant', constant_values=0))

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

In [31]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.7 == 7 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [32]:
arr=np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [33]:
arr=np.zeros((6,6),dtype=int)
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [34]:
arr=np.unravel_index(100,(8,9,10))
print(arr)

(np.int64(1), np.int64(1), np.int64(0))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [37]:
my_arr=np.array([[1,0],[3,4]])
print(np.tile(my_arr,(3,3)))

[[1 0 1 0 1 0]
 [3 4 3 4 3 4]
 [1 0 1 0 1 0]
 [3 4 3 4 3 4]
 [1 0 1 0 1 0]
 [3 4 3 4 3 4]]


#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [38]:
my_arr=np.random.random((6,6))
print(my_arr)
my_arr=(my_arr-np.mean(my_arr))/np.std(my_arr)
print(my_arr)

[[0.23500116 0.12334331 0.3607998  0.06787644 0.69978013 0.49463057]
 [0.37319668 0.56988431 0.82017132 0.81382688 0.02213714 0.96576699]
 [0.78377    0.14560859 0.57126323 0.07401137 0.06257517 0.41624895]
 [0.90629465 0.83213498 0.06261486 0.47531121 0.90560545 0.33753737]
 [0.31003671 0.66785455 0.01405782 0.86060152 0.27760519 0.79896781]
 [0.06812611 0.35525506 0.36563811 0.67698798 0.22422712 0.00888706]]
[[-0.66094141 -1.02550273 -0.25021063 -1.20660127  0.85655536  0.18674494]
 [-0.20973498  0.43244735  1.24963088  1.22891639 -1.35593944  1.72499868]
 [ 1.1307811  -0.95280689  0.43694949 -1.18657081 -1.22390984 -0.06916993]
 [ 1.53082234  1.28869207 -1.22378024  0.12366752  1.52857211 -0.32616215]
 [-0.41595141  0.7523188  -1.3823183   1.38163491 -0.52183984  1.18040172]
 [-1.20578609 -0.26831413 -0.23441362  0.78213931 -0.69611852 -1.39920076]]


#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

In [39]:
arr=np.array([1,2,3,4,5])
print("Number of elements: ",arr.size)
print("Length of one array element in bytes: ",arr.itemsize)
print("Total bytes consumed by the elements of the array: ",arr.nbytes)

Number of elements:  5
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  40


#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [46]:
arr1=np.ones((6,3))
arr2=np.ones((3,4))
print((np.dot(arr1,arr2)))

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [47]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[(arr>3) & (arr<8)]*=-1
print(arr)

[ 1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [48]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [49]:
arr_a=np.array([1,2])
arr_b=np.array([4,5])
print(arr_a>arr_b)
print(arr_a>=arr_b)
print(arr_a<arr_b)
print(arr_a<=arr_b)

[False False]
[False False]
[ True  True]
[ True  True]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [59]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print( np.array([np.nan]).astype(int).astype(float))

a = np.array([1, 2, 3])
print("a =", a)
print("a**a =", a**a)
print("a << a >> 2 =", a << a >> 2)
print("a <- a =", a < -a)
print("1j * a =", 1j * a)
print("a / 1 / 1 =", a / 1 / 1)


nan
0
[-9.22337204e+18]
a = [1 2 3]
a**a = [ 1  4 27]
a << a >> 2 = [0 2 6]
a <- a = [False False False]
1j * a = [0.+1.j 0.+2.j 0.+3.j]
a / 1 / 1 = [1. 2. 3.]


/tmp/ipython-input-362183637.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-362183637.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-362183637.py:3: RuntimeWarning: invalid value encountered in cast
  print( np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [57]:
arr=np.random.uniform(-9, +9, 9)
print(arr)
print(np.copysign(np.ceil(np.abs(arr)), arr))

[-1.17014247 -0.22929981 -7.81333936 -5.55902365  1.84098696 -8.54488252
 -4.68185605  2.53716788 -1.6864523 ]
[-2. -1. -8. -6.  2. -9. -5.  3. -2.]


#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [56]:
array1=np.array([6,2,3,4,5])
array2=np.array([4,5,6,7,8])
array3=np.intersect1d(array1,array2)
print(array3)

[4 5 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))